name: adi_helpers
description: A bunch of random helperssss
version: 1.0.0
author: Adrian
  
environment:  
  sdk: ">=2.6.1 <3.0.0"

dependencies:  
  quiver: ^2.0.1 
  dartz: ^0.8.9
  basic_utils: ^2.4.8

dev_dependencies:  
  test: ^1.0.0
