name: adi_helpers
description: A bunch of random helpers
version: 1.0.6
author: Adrian
  
environment:  
  sdk: ">=2.6.1 <3.0.0"

dependencies:  
  quiver: ^2.0.1 
  dartz: ^0.8.9
  basic_utils: ^2.4.8
  intl: ^0.16.1

dev_dependencies:
  test: ^1.15.1
  build_runner: ^1.10.0


