name: adi_helpers
description: A bunch of random helpers
version: 1.2.2

environment:  
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  quiver: ^3.0.0-nullsafety.3
  dartz: ^0.10.0-nullsafety.0
#  basic_utils: ^2.4.8
  intl: ^0.19.0
  collection: ^1.15.0-nullsafety.5
  dartx: ^1.2.0
  equatable: ^2.0.5

dev_dependencies:
  meta: ^1.11.0
  test: ^1.24.8
  build_runner: ^2.4.6

