name: adi_helpers
description: A bunch of random helpers
version: 1.2.2

environment:  
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  quiver: ^3.2.2
  dartz: ^0.10.1
#  basic_utils: ^2.4.8
  intl: ^0.20.2
#  collection: ^1.15.0-nullsafety.5
  dartx: ^1.2.0
  equatable: ^2.0.7

dependency_overrides:
  file: ^7.0.0

dev_dependencies:
  meta: ^1.17.0
  test: ^1.26.2
  build_runner: ^2.4.15

