name: adi_helpers
description: A bunch of random helpers
version: 1.0.7-nullsafety2

environment:  
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  quiver: ^3.0.0-nullsafety.3
  dartz: ^0.10.0-nullsafety.0
#  basic_utils: ^2.4.8
  intl: ^0.17.0-nullsafety.2
  collection: ^1.15.0-nullsafety.5
  dartx: ^0.6.0

dev_dependencies:
  test: ^1.16.0-nullsafety.16
  build_runner: ^1.7.3


