name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup adi_helpers
        working-directory: ./
        run:  |
          pub get
          pub run build_runner build --delete-conflicting-outputs
      - name: Run tests adi_helpers
        working-directory: ./
        run: pub run test
